server:
  port: 9090

spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.61.90:3306/news?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: PENG
    password: PENGmysqlserver666

#showSql
logging:
  level:
    com:
      peng:
        news:
          mapper: debug

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.peng.news.model
  configuration:
    map-underscore-to-camel-case: true
#    cache-enabled: false
#    local-cache-scope: statement

#系统内部配置
news:
  system:
    max-review-level: 6
